[package]
name = "harness"
entry = "src/main.coil"
source-roots = ["src", "tests", "tools", "/Users/jimmyhmiller/Documents/Code/projects/coil/src/experiments/httptap"]

[test]
roots = ["tests"]
suffixes = ["_test.coil"]

[link]
libs = ["curl"]
