#!/usr/bin/env python3
"""Generate tests/bus_cc_conformance_test.coil from the reference implementation.

The Claude Code receiver re-renders every envelope it parses and compares it
byte-for-byte with what arrived, so our renderer has to agree with the reference
exactly -- not merely be self-consistent. A test suite written by hand from a
reading of the protocol cannot establish that; it can only establish that the
reader and the writer share an assumption.

So the expected strings here are not authored. They are produced by running the
reference client (ccpeer/vectors.js, which calls ccpeer/protocol.js) and emitted
into Coil literals mechanically, which also removes transcription as a failure
mode. Regenerate after touching either side:

    python3 scripts/generate_cc_conformance.py

Requires node, which is why this is a generator rather than part of `coil test`:
the committed output runs in the ordinary suite with no node dependency.
"""

import json
import pathlib
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
VECTORS = ROOT / "docs/claude-code-cross-session-protocol/ccpeer/vectors.js"
OUT = ROOT / "tests/bus_cc_conformance_test.coil"

# How each case name is constructed on the Coil side. Mirrors the spec list in
# vectors.js; keep the two in step. A value is a list of (field, coil-literal)
# pairs plus the body.
ENVELOPE_CASES = {
    "from-only": [("from", '"uds:/tmp/cc-socks/1.sock"'), ("body", '"hi"')],
    "from-name-mode": [
        ("from", '"uds:/tmp/x.sock"'),
        ("from-name", '"harness"'),
        ("from-mode", '"bypass"'),
        ("body", '"do it"'),
    ],
    "name-quotes-angles": [("from-name", '"ev\\"il<>"'), ("body", '"x"')],
    "name-200z": [("from-name", "(repeated allocator 122 200)"), ("body", '"x"')],
    "name-exactly-64": [("from-name", "(repeated allocator 122 64)"), ("body", '"x"')],
    "name-65": [("from-name", "(repeated allocator 122 65)"), ("body", '"x"')],
    "name-accents-100": [("from-name", "(repeated-accent allocator 100)"), ("body", '"x"')],
    "name-control": [("from-name", '"ab\\xE2\\x80\\x8Bc\\xEF\\xBB\\xBFd"'), ("body", '"x"')],
    "name-spaces": [("from-name", '"   padded   "'), ("body", '"x"')],
    "name-all-stripped": [("from-name", '"<<>>"'), ("body", '"x"')],
    "body-closetag": [
        ("from", '"uds:/tmp/x.sock"'),
        ("body", '"before </cross-session-message> after"'),
    ],
    "body-closetag-upper": [
        ("from", '"uds:/tmp/x.sock"'),
        ("body", '"a </Cross-Session-Message> b"'),
    ],
    "body-closetag-nospace": [
        ("from", '"uds:/tmp/x.sock"'),
        ("body", '"a </cross-session-message b"'),
    ],
    "body-closetag-eos": [
        ("from", '"uds:/tmp/x.sock"'),
        ("body", '"a </cross-session-message"'),
    ],
    "body-closetag-plural": [
        ("from", '"uds:/tmp/x.sock"'),
        ("body", '"a </cross-session-messages> b"'),
    ],
    "body-other-tag": [("from", '"uds:/tmp/x.sock"'), ("body", '"a </other> b"')],
    "body-empty": [("from", '"uds:/tmp/x.sock"'), ("body", '""')],
    "body-multiline": [
        ("from", '"uds:/tmp/x.sock"'),
        ("body", '"one\\ntwo\\n\\nfour"'),
    ],
    "no-attrs": [("body", '"hi"')],
    "session-hop": [
        ("from", '"uds:/tmp/x.sock"'),
        ("from-session", '"abc-123_XYZ"'),
        ("hop-chain", "(hop-ids-ab allocator)"),
        ("from-name", '"n"'),
        ("from-mode", '"prompting"'),
        ("body", '"b"'),
    ],
    "session-invalid": [
        ("from-session", '"not a session"'),
        ("hop-chain", '"nothex"'),
        ("from-mode", '"root"'),
        ("body", '"x"'),
    ],
    "hop-uppercase": [("hop-chain", "(hop-ids-upper allocator 1)"), ("body", '"x"')],
    "hop-33": [("hop-chain", "(hop-ids allocator 33)"), ("body", '"x"')],
    "hop-32": [("hop-chain", "(hop-ids allocator 32)"), ("body", '"x"')],
}

ADDRESS_CASES = {
    "addr-plain": '"/tmp/cc-socks/1.sock"',
    "addr-space": '"/tmp/cc socks/1.sock"',
    "addr-percent": '"/tmp/100%/x.sock"',
    "addr-accent": '"/tmp/café.sock"',
    "addr-bracket": '"/tmp/a[b].sock"',
    "addr-question": '"/tmp/a?b.sock"',
}

PREAMBLE = '''\
;; GENERATED by scripts/generate_cc_conformance.py -- do not edit by hand.
;;
;; Every expected string below is the reference implementation's actual output,
;; captured by running ccpeer/vectors.js. That matters more than it looks: the
;; Claude Code receiver validates an envelope by re-rendering what it parsed and
;; comparing byte-for-byte, so a renderer that is merely self-consistent passes
;; its own round-trip tests and still has every message it sends silently
;; demoted to anonymous text. Only a differential test against the reference can
;; catch that, and only if the expectations are not authored by the same reading
;; that produced the implementation.
;;
;; Regenerate with: python3 scripts/generate_cc_conformance.py
(module harness-bus-cc-conformance-test)

(import "coil.alloc" :as alloc :use *)
(import "coil.assert" :use *)
(import "coil.match" :use *)
(import "coil.result" :use *)
(import "coil.slice" :use *)
(import "coil.str" :use *)
(import "harness-bus-cc-address" :use *)
(import "harness-bus-cc-envelope" :use *)

(defn repeated [(allocator (ptr Allocator)) (byte i64) (count i64)] (-> (slice u8))
  (let [(mut buffer) (sb-new allocator)
        (mut i) 0]
    (loop (if (>= (load i) count)
              (break)
              (do (sb-push-byte! (mut buffer) (cast u8 byte))
                  (store! i (+ (load i) 1)))))
    (sb-finish! (mut buffer))))

;; U+00E9, to prove the 64-code-point clamp is not a 64-byte clamp.
(defn repeated-accent [(allocator (ptr Allocator)) (count i64)] (-> (slice u8))
  (let [(mut buffer) (sb-new allocator)
        (mut i) 0]
    (loop (if (>= (load i) count)
              (break)
              (do (sb-push-byte! (mut buffer) (cast u8 195))
                  (sb-push-byte! (mut buffer) (cast u8 169))
                  (store! i (+ (load i) 1)))))
    (sb-finish! (mut buffer))))

(defn hop-ids-of [(allocator (ptr Allocator)) (count i64) (byte i64)] (-> (slice u8))
  (let [(mut buffer) (sb-new allocator)
        (mut i) 0]
    (loop (if (>= (load i) count)
              (break)
              (do
                (when (> (load i) 0)
                  (sb-push-byte! (mut buffer) (cast u8 44))
                  0)
                (sb-push-str! (mut buffer) (repeated allocator byte 24))
                (store! i (+ (load i) 1)))))
    (sb-finish! (mut buffer))))

(defn hop-ids [(allocator (ptr Allocator)) (count i64)] (-> (slice u8))
  (hop-ids-of allocator count 97))

(defn hop-ids-upper [(allocator (ptr Allocator)) (count i64)] (-> (slice u8))
  (hop-ids-of allocator count 65))

;; Two distinct ids, so the separator is proved to join different values rather
;; than being invisible inside a run of one repeated character.
(defn hop-ids-ab [(allocator (ptr Allocator))] (-> (slice u8))
  (let [(mut buffer) (sb-new allocator)]
    (sb-push-str! (mut buffer) (repeated allocator 97 24))
    (sb-push-byte! (mut buffer) (cast u8 44))
    (sb-push-str! (mut buffer) (repeated allocator 98 24))
    (sb-finish! (mut buffer))))
'''


def coil_string(text: str) -> str:
    out = ['"']
    for ch in text:
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\r":
            out.append("\\r")
        elif ch == "\t":
            out.append("\\t")
        else:
            out.append(ch)
    out.append('"')
    return "".join(out)


def test_name(case: str) -> str:
    return "the-reference-renders-" + case.replace("_", "-")


def main() -> int:
    if not VECTORS.exists():
        print(f"missing {VECTORS}", file=sys.stderr)
        return 1
    raw = subprocess.run(
        ["node", str(VECTORS)], capture_output=True, text=True, check=True
    ).stdout
    expected = json.loads(raw)

    missing = (set(ENVELOPE_CASES) | set(ADDRESS_CASES)) - set(expected)
    if missing:
        print(f"vectors.js did not emit: {sorted(missing)}", file=sys.stderr)
        return 1

    parts = [PREAMBLE]

    for case, fields in ENVELOPE_CASES.items():
        want = expected[case]
        setters = "\n".join(
            f"           (store! (field envelope {name}) "
            + (value if name == "body" else f"(Some {value}))")
            + (")" if name == "body" else "")
            for name, value in fields
        )
        parts.append(
            f"""
(deftest {test_name(case)}
         (let [allocator (malloc-allocator)
               envelope (alloc/stack CcEnvelope)]
           (cc-envelope-init! envelope)
{setters}
           (assert (str-eq (cc-envelope-render allocator envelope)
                           {coil_string(want)}))))
"""
        )

    for case, path in ADDRESS_CASES.items():
        parts.append(
            f"""
(deftest {test_name(case)}
         (let [allocator (malloc-allocator)]
           (assert (str-eq (cc-uds-address allocator {path})
                           {coil_string(expected[case])}))))
"""
        )

    # Everything the reference produces must also parse back, and parsing is
    # defined as "re-rendering reproduces the input". A vector that renders
    # correctly but fails to parse would mean our own output is unreadable to us.
    parts.append(
        """
;; Whatever the reference emits, we must be able to read -- and reading is
;; defined as re-rendering to the identical bytes. This closes the loop: the
;; tests above prove we write what it writes, and this proves we accept it.
(deftest every-reference-vector-parses-and-re-renders-identically
"""
    )
    for case in ENVELOPE_CASES:
        parts.append(
            f"""         (let [allocator (malloc-allocator)
               parsed (alloc/stack CcEnvelope)
               text {coil_string(expected[case])}]
           (assert (cc-envelope-parse allocator text parsed))
           (assert (str-eq (cc-envelope-render allocator parsed) text)))
"""
        )
    parts.append("         )\n")

    OUT.write_text("".join(parts))
    print(f"wrote {OUT.relative_to(ROOT)} ({len(ENVELOPE_CASES) + len(ADDRESS_CASES)} vectors)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
