#!/usr/bin/env python3
"""Generate deterministic Coil terminal-width predicates from the Unicode UCD."""

from __future__ import annotations

import argparse
import pathlib
import urllib.request


UNICODE_VERSION = "17.0.0"
UCD_ROOT = f"https://www.unicode.org/Public/{UNICODE_VERSION}/ucd"


def fetch(name: str) -> str:
    with urllib.request.urlopen(f"{UCD_ROOT}/{name}", timeout=30) as response:
        return response.read().decode("utf-8")


def merge(ranges: list[tuple[int, int]]) -> list[tuple[int, int]]:
    merged: list[tuple[int, int]] = []
    for start, end in sorted(ranges):
        if merged and start <= merged[-1][1] + 1:
            merged[-1] = (merged[-1][0], max(end, merged[-1][1]))
        else:
            merged.append((start, end))
    return merged


def zero_width_ranges(data: str) -> list[tuple[int, int]]:
    result: list[tuple[int, int]] = []
    range_start: int | None = None
    range_category: str | None = None
    for line in data.splitlines():
        fields = line.split(";")
        codepoint = int(fields[0], 16)
        name = fields[1]
        category = fields[2]
        if name.endswith(", First>"):
            range_start = codepoint
            range_category = category
        elif name.endswith(", Last>"):
            if range_category in {"Mn", "Me", "Cf"}:
                assert range_start is not None
                result.append((range_start, codepoint))
            range_start = None
            range_category = None
        elif category in {"Mn", "Me", "Cf"}:
            result.append((codepoint, codepoint))

    # Hangul medial and final Jamo combine with a preceding leading consonant.
    result.append((0x1160, 0x11FF))
    return merge(result)


def wide_ranges(data: str) -> list[tuple[int, int]]:
    result: list[tuple[int, int]] = []
    for raw in data.splitlines():
        line = raw.split("#", 1)[0].strip()
        if not line:
            continue
        codepoints, property_name = [part.strip() for part in line.split(";", 1)]
        if property_name not in {"W", "F"}:
            continue
        if ".." in codepoints:
            start, end = (int(value, 16) for value in codepoints.split(".."))
        else:
            start = end = int(codepoints, 16)
        result.append((start, end))
    return merge(result)


def condition(start: int, end: int) -> str:
    if start == end:
        return f"(= codepoint {start})"
    return f"(and (>= codepoint {start}) (<= codepoint {end}))"


def predicate(name: str, ranges: list[tuple[int, int]], chunk_size: int = 20) -> str:
    chunks = [ranges[index : index + chunk_size] for index in range(0, len(ranges), chunk_size)]
    output: list[str] = []
    helpers: list[str] = []
    for index, chunk in enumerate(chunks):
        helper = f"{name}-chunk-{index}"
        helpers.append(f"({helper} codepoint)")
        expression = "false"
        for start, end in reversed(chunk):
            expression = f"(or {condition(start, end)} {expression})"
        output.append(f"(defn {helper} [(codepoint i64)] (-> bool)\n  {expression})")

    aggregate = "false"
    for call in reversed(helpers):
        aggregate = f"(or {call} {aggregate})"
    output.append(f"(defn {name} [(codepoint i64)] (-> bool)\n  {aggregate})")
    return "\n\n".join(output)


def generate() -> str:
    zero = zero_width_ranges(fetch("UnicodeData.txt"))
    wide = wide_ranges(fetch("EastAsianWidth.txt"))
    return "\n".join(
        [
            "(module harness-tui-unicode-width)",
            "",
            ";; Generated by scripts/generate_unicode_width.py from the Unicode",
            f";; {UNICODE_VERSION} UnicodeData.txt and EastAsianWidth.txt files.",
            ";; Do not edit this file manually.",
            "",
            predicate("unicode-zero-width?", zero),
            "",
            predicate("unicode-wide?", wide),
            "",
        ]
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--output",
        type=pathlib.Path,
        default=pathlib.Path("src/tui/unicode_width.coil"),
    )
    args = parser.parse_args()
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(generate(), encoding="utf-8")


if __name__ == "__main__":
    main()
